-- Baseline: the schema exactly as `ddl-auto=update` left it, captured
-- 2026-09-30 by pg_dump --schema-only against the running database.
--
-- DERIVED FROM THE LIVE SCHEMA, NOT FROM THE ENTITY CLASSES. Generating it
-- from the entities would describe what Hibernate WOULD create rather than
-- what it DID create across months of incremental updates; where those differ,
-- the difference is the orphan-column problem this migration exists to end,
-- and generating from entities would have erased the evidence.
--
-- They did not differ: all 6 tables and all 45 columns matched the entities
-- exactly, with no orphans.
--
-- Constraint names are Hibernate's own generated hashes, reproduced verbatim
-- so a database built from this file is identical to the one built by update.

CREATE TABLE public.game (
    id bigint NOT NULL,
    game_date date,
    nba_game_id bigint,
    played boolean NOT NULL,
    away_team_id bigint,
    home_team_id bigint
);

ALTER TABLE public.game ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.player (
    id bigint NOT NULL,
    name character varying(255)
);

CREATE TABLE public.player_prop_prediction (
    id bigint NOT NULL,
    model_used character varying(255),
    predicted_assists double precision NOT NULL,
    predicted_at timestamp(6) with time zone,
    predicted_points double precision NOT NULL,
    predicted_pra double precision NOT NULL,
    predicted_rebounds double precision NOT NULL,
    predicted_threes_made double precision NOT NULL,
    game_id bigint,
    player_id bigint,
    team_id bigint
);

ALTER TABLE public.player_prop_prediction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_prop_prediction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.prediction (
    id bigint NOT NULL,
    assist_margin double precision NOT NULL,
    data_as_of date,
    home_margin double precision NOT NULL,
    home_win_probability double precision NOT NULL,
    predicted_at timestamp(6) with time zone,
    rebound_margin double precision NOT NULL,
    stale boolean NOT NULL,
    total_assists double precision NOT NULL,
    total_points double precision NOT NULL,
    total_rebounds double precision NOT NULL,
    game_id bigint
);

ALTER TABLE public.prediction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prediction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.quarter_half_prediction (
    id bigint NOT NULL,
    data_as_of date,
    half1_spread double precision NOT NULL,
    half1_total double precision NOT NULL,
    half1_winner_probability double precision NOT NULL,
    predicted_at timestamp(6) with time zone,
    q1_spread double precision NOT NULL,
    q1_total double precision NOT NULL,
    q1_winner_probability double precision NOT NULL,
    stale boolean NOT NULL,
    game_id bigint
);

ALTER TABLE public.quarter_half_prediction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quarter_half_prediction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.team (
    id bigint NOT NULL,
    abbreviation character varying(255),
    name character varying(255)
);

ALTER TABLE ONLY public.game
    ADD CONSTRAINT game_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.player
    ADD CONSTRAINT player_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.player_prop_prediction
    ADD CONSTRAINT player_prop_prediction_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.prediction
    ADD CONSTRAINT prediction_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.quarter_half_prediction
    ADD CONSTRAINT quarter_half_prediction_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.team
    ADD CONSTRAINT team_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.game
    ADD CONSTRAINT fk51yuyu3ukyq5e8nsvywbof2ws FOREIGN KEY (home_team_id) REFERENCES public.team(id);

ALTER TABLE ONLY public.player_prop_prediction
    ADD CONSTRAINT fk5n5f8t71b0xadg16ahnriubwa FOREIGN KEY (player_id) REFERENCES public.player(id);

ALTER TABLE ONLY public.prediction
    ADD CONSTRAINT fka9vbn5d8tbpw5wt2xmdeon647 FOREIGN KEY (game_id) REFERENCES public.game(id);

ALTER TABLE ONLY public.game
    ADD CONSTRAINT fkaowpughmnfa6ifikwfy6wf4g2 FOREIGN KEY (away_team_id) REFERENCES public.team(id);

ALTER TABLE ONLY public.player_prop_prediction
    ADD CONSTRAINT fkbl74wd2kjfonqs0ufrsqwogx0 FOREIGN KEY (game_id) REFERENCES public.game(id);

ALTER TABLE ONLY public.quarter_half_prediction
    ADD CONSTRAINT fkp511ckuabds6yu3u7wxgukn3j FOREIGN KEY (game_id) REFERENCES public.game(id);

ALTER TABLE ONLY public.player_prop_prediction
    ADD CONSTRAINT fkr5jy9cp775g8rb999glfdv8if FOREIGN KEY (team_id) REFERENCES public.team(id);
