-- WNBA support: a league column on team, and a table of its own for WNBA
-- predictions.
--
-- The first migration written as a migration rather than baselined from a
-- schema Hibernate had already built. V1 reproduced what ddl-auto=update had
-- made over months; this one is the forward direction that arrangement exists
-- for, and ddl-auto=validate will refuse to boot if the entities and these
-- statements disagree.

-- Existing rows are all NBA, so the default backfills them in one statement
-- and no data migration is needed. NOT NULL because a team with no league is
-- not a meaningful row - every query that filters by league would silently
-- drop it, which is the quiet kind of wrong.
ALTER TABLE public.team
    ADD COLUMN league character varying(255) NOT NULL DEFAULT 'NBA';

-- A SEPARATE TABLE, NOT EXTRA COLUMNS ON prediction.
--
-- The WNBA prices three markets against the NBA's seven, so folding it in
-- would mean seven nullable columns where four are always null and three
-- carry a different league's numbers, with nothing in the row saying which.
-- That is the shape CLAUDE.md section 8 rejected for quarter/half and player
-- props, and the reasoning has not changed: a union type that is mostly nulls
-- whichever way it is written.
--
-- The game table IS reused. One Game row per matchup per date whichever
-- markets are priced, and WNBA team ids are disjoint from NBA ones
-- (1611661313-1611661332 against 1610612737-1610612766, verified empty
-- intersection), so a WNBA fixture cannot collide with an NBA one.
CREATE TABLE public.wnba_prediction (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_id bigint,
    home_win_probability double precision NOT NULL,
    home_margin double precision NOT NULL,
    total_points double precision NOT NULL,
    data_as_of date,
    stale boolean NOT NULL,
    predicted_at timestamp(6) with time zone
);

ALTER TABLE ONLY public.wnba_prediction
    ADD CONSTRAINT wnba_prediction_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.wnba_prediction
    ADD CONSTRAINT fk_wnba_prediction_game FOREIGN KEY (game_id)
    REFERENCES public.game(id);
