-- The G League, the third league to share this schema.
--
-- Its own prediction table rather than columns on `prediction`: three markets
-- against the NBA's seven would mean four always-null columns and nothing in
-- the row saying which league it was. The `game` table IS reused, which is
-- safe because the three leagues' team-id ranges are disjoint - the NBA's
-- 1610612737-1610612766, the WNBA's 1611661313-1611661332 and the G League's
-- 1612709889 upward - and TeamSeeder asserts that at startup rather than
-- assuming it.
--
-- `team.league` already exists from V2 and needs no change; G League rows
-- simply carry 'GLEAGUE'.
--
-- The nullability pattern follows the entity, as V1's did: a NOT NULL column
-- is a Java primitive and a nullable one is an object type. data_as_of is
-- nullable because it is a LocalDate, not because anyone decided a prediction
-- may have no cutoff.

CREATE TABLE gleague_prediction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_id BIGINT,
    home_win_probability DOUBLE PRECISION NOT NULL,
    home_margin DOUBLE PRECISION NOT NULL,
    total_points DOUBLE PRECISION NOT NULL,
    data_as_of DATE,
    stale BOOLEAN NOT NULL,
    predicted_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_gleague_prediction PRIMARY KEY (id)
);

ALTER TABLE gleague_prediction
    ADD CONSTRAINT fk_gleague_prediction_game
    FOREIGN KEY (game_id) REFERENCES game (id);
