-- The NFL, the fourth league to share this schema and the first sport that is
-- not basketball.
--
-- Its own prediction table rather than columns on `prediction`, for the reason
-- V2 and V3 give: three markets against the NBA's seven would mean four
-- always-null columns and nothing in the row saying which league it was. The
-- `game` table IS reused, which is safe because the four leagues' team-id
-- ranges are disjoint - the NBA's 1610612737-1610612766, the WNBA's
-- 1611661313-1611661332, the G League's 1612709889 upward and the NFL's
-- 1613000001-1613000032 - and TeamSeeder asserts all six pairs at startup
-- rather than assuming it.
--
-- THE NFL'S IDS ARE PROJECT-ASSIGNED, WHICH NO OTHER LEAGUE'S ARE. The other
-- three take TEAM_ID from nba_api. The NFL source carries no stable team id at
-- all, so phase 1 authored the range in nfl_franchises.py and chose it to sit
-- clear of the three already in use.
--
-- `team.league` already exists from V2 and needs no change; NFL rows carry
-- 'NFL'.
--
-- WHAT IS STORED AND WHAT IS NOT. The three market values, the cutoff and the
-- staleness are per-row facts and are stored. The winner interpretation
-- (P(home wins | not tied)), the per-market model identifier and the manifest's
-- "TIES Elo alone" note are identical on every row this table will ever hold,
-- so by the rule in CLAUDE.md section 8 they are constants about which model
-- produced a number and are attached at response-build time instead.
--
-- `week` IS stored, and it is the exception that proves the rule: it varies per
-- row, it is a feature the model actually read, and an NFL result is discussed
-- by week rather than by date. Season is recoverable from game.game_date and is
-- not duplicated here.
--
-- The nullability pattern follows the entity, as V1's did: a NOT NULL column is
-- a Java primitive and a nullable one is an object type.

CREATE TABLE nfl_prediction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_id BIGINT,
    home_win_probability DOUBLE PRECISION NOT NULL,
    home_margin DOUBLE PRECISION NOT NULL,
    total_points DOUBLE PRECISION NOT NULL,
    week INTEGER NOT NULL,
    data_as_of DATE,
    stale BOOLEAN NOT NULL,
    predicted_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_nfl_prediction PRIMARY KEY (id)
);

ALTER TABLE nfl_prediction
    ADD CONSTRAINT fk_nfl_prediction_game
    FOREIGN KEY (game_id) REFERENCES game (id);
